<template>
  <div class="container h-100">
    <div class="row align-items-center h-100" style="display: block;">
      <div class="col-12 mx-auto">
        <div class="jumbotron text-center">
          <h1 class="display-4">Generate Netlify redirect config</h1>
          <p class="lead">Note: <span class="highlight">The generated config will work if you use Netlify to manage DNS for your custom domain</span></p>
        </div>
      </div>
      <div class="col-4 mx-auto">
        <div class="form-group">
          <label for="netlifyDomain">Netlify domain</label>
          <div class="input-group">
            <input type="text" class="form-control" id="netlifyDomain" placeholder="example" v-model="netlifyDomain">
            <div class="input-group-append">
              <div class="input-group-text">.netlify.com</div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="customDomain">Custom domain</label>
          <input type="text" class="form-control" id="customDomain" placeholder="example.com" v-model="customDomain">
        </div>
      </div>
      <div class="col-8 mx-auto">
        <button
          type="button"
          :disabled="netlifyConfig === ''"
          class="btn btn-primary my-2"
          v-clipboard:copy="netlifyConfig"
          v-clipboard:success="onCopy"
          v-clipboard:error="onError">
          Copy
        </button>
        <p v-if="copySucceeded === true">Netlify config was copied!</p>
        <p v-if="copySucceeded === false">Press CTRL+C to copy.</p>
        <textarea disabled class="form-control" rows="37" v-model="netlifyConfig" placeholder="# Generated by https://playground.safestudio.tech/generate-netlify-redirect-config"></textarea>
        <button
          type="button"
          :disabled="netlifyConfig === ''"
          class="btn btn-primary my-2"
          v-clipboard:copy="netlifyConfig"
          v-clipboard:success="onCopy"
          v-clipboard:error="onError">
          Copy
        </button>
      </div>
      <footer class="footer">
        <p>Copright &copy; 2019 by <span class="brand">SAFE Studio Team.</span></p>
      </footer>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      netlifyDomain: '',
      customDomain: '',
      copySucceeded: null,
    }
  },
  computed: {
    netlifyConfig() {
      if (this.netlifyDomain.length === 0 || this.customDomain.length === 0 || !this.isValidDomain(this.customDomain)) {
        return ''
      }
      return `# Generated by https://playground.safestudio.tech/generate-netlify-redirect-config
[[redirects]]
  from = "http://${this.netlifyDomain}.netlify.com"
  to = "https://${this.customDomain}"
[[redirects]]
  from = "http://${this.netlifyDomain}.netlify.com/*"
  to = "https://${this.customDomain}/:splat"
  status = 301
[[redirects]]
  from = "${this.netlifyDomain}.netlify.com"
  to = "https://${this.customDomain}"
[[redirects]]
  from = "${this.netlifyDomain}.netlify.com/*"
  to = "https://${this.customDomain}/:splat"
  status = 301
[[redirects]]
  from = "https://${this.netlifyDomain}.netlify.com"
  to = "https://${this.customDomain}"
[[redirects]]
  from = "https://${this.netlifyDomain}.netlify.com/*"
  to = "https://${this.customDomain}/:splat"
  status = 301
[[redirects]]
  from = "http://${this.customDomain}"
  to = "https://${this.customDomain}"
[[redirects]]
  from = "http://${this.customDomain}/*"
  to = "https://${this.customDomain}/:splat"
  status = 301
[[redirects]]
  from = "${this.customDomain}"
  to = "https://${this.customDomain}"
[[redirects]]
  from = "${this.customDomain}/*"
  to = "https://${this.customDomain}/:splat"
  status = 301`
    }
  },
  methods: {
    isValidDomain: domain => {
      const regex = new RegExp(/^((?:(?:(?:\w[\.\-\+]?)*)\w)+)((?:(?:(?:\w[\.\-\+]?){0,62})\w)+)\.(\w{2,6})$/);
      return domain.match(regex);
    },
    onCopy: function (e) {
      this.copySucceeded = true;
      alert('Netlify config was copied!');
    },
    onError: function (e) {
      this.copySucceeded = false;
      alert('Failed to copy texts!')
    },
  }
}
</script>
<style>
#__layout {
  height: 100vh;
}
.jumbotron {
  background-color: #fff;
}
.text-center .dropdown-menu {
   left: 50%;
   transform: translateX(-50%);
}
.footer {
  padding: 2rem;
  text-align: center;
}
.footer p:last-child {
  margin-bottom: 0;
}

.brand {
  color: blue;
  font-weight: bold;
}
</style>

